openapi: 3.0.3
info:
  title: Cape of Good Place Names Service
  description: This is a stateless service for performing various geotranslation operations,
    moving between how people describe places and codified coordinate systems.
  contact:
    name: City of Cape Town Data Science Unit
    url: https://github.com/cityofcapetown/cape-of-good-place-names
    email: opmdata+cogpn-support@capetown.gov.za
  license:
    name: MIT
    url: https://raw.githubusercontent.com/cityofcapetown/cape-of-good-place-names/master/LICENSE
  version: 0.1.0
servers:
- url: http://localhost:8000
  description: local dev server
- url: https://cogpn-beta.capetown.gov.za
  description: integration testing server
- url: https://cogpn.capetown.gov.za
  description: prod server
security:
- basicAuth: []
paths:
  /v1/scrub:
    get:
      summary: Extract meaningful phrases or identifiers from free form addresses
      operationId: scrub
      parameters:
      - name: address
        in: query
        description: Free form address string
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: An array of scrubbed results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScrubResults'
        "401":
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: cape_of_good_place_names.controllers.default_controller
  /v1/geocode:
    get:
      summary: Translate a free form address into a spatial coordinate
      operationId: geocode
      parameters:
      - name: address
        in: query
        description: Free form address string to geocode
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: An array of geocoded results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeocodeResults'
        "401":
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: cape_of_good_place_names.controllers.default_controller
  /v1/boundary_lookup:
    get:
      summary: Translate a spatial identifier into a description of space
      operationId: geolookup
      parameters:
      - name: spatial_id
        in: query
        description: spatial identifier to look up in spatial dataset
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: spatial_dataset_id
        in: query
        description: dataset from which to look up spatial identifier
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: An array of geolookup results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeolookupResults'
        "401":
          description: Authentication information is missing or invalid
          headers:
            WWW_Authenticate:
              style: simple
              explode: false
              schema:
                type: string
        "404":
          description: Either the spatial identifier or spatial dataset don't exist.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: cape_of_good_place_names.controllers.default_controller
components:
  schemas:
    ScrubResult:
      required:
      - confidence
      - scrubbed_value
      - scrubber_id
      type: object
      properties:
        scrubber_id:
          type: string
          description: Identifier for the scrubber
        scrubbed_value:
          type: string
        confidence:
          type: number
          format: float
      example:
        scrubber_id: scrubber_id
        confidence: 0.8008282
        scrubbed_value: scrubbed_value
    ScrubResults:
      required:
      - id
      - results
      - timestamp
      type: object
      properties:
        id:
          type: string
          description: UUID describing the transaction
        timestamp:
          type: string
          description: Server time of the transaction
          format: date-time
        results:
          type: array
          description: Array of Scrub results
          items:
            $ref: '#/components/schemas/ScrubResult'
      example:
        id: id
        results:
        - scrubber_id: scrubber_id
          confidence: 0.8008282
          scrubbed_value: scrubbed_value
        - scrubber_id: scrubber_id
          confidence: 0.8008282
          scrubbed_value: scrubbed_value
        timestamp: 2000-01-23T04:56:07.000+00:00
    GeocodeResult:
      required:
      - confidence
      - geocoded_value
      - geocoder_id
      type: object
      properties:
        geocoder_id:
          type: string
          description: Identifier for the geocoder
        geocoded_value:
          type: object
          description: Resulting GeoJSON string from the GeoCoder
        confidence:
          type: number
          format: float
      example:
        confidence: 0.8008282
        geocoder_id: geocoder_id
        geocoded_value: {}
    GeocodeResults:
      required:
      - id
      - results
      - timestamp
      type: object
      properties:
        id:
          type: string
          description: UUID describing the transaction
        timestamp:
          type: string
          description: Server time of the transaction
          format: date-time
        results:
          type: array
          description: Array of Geocoding results
          items:
            $ref: '#/components/schemas/GeocodeResult'
      example:
        id: id
        results:
        - confidence: 0.8008282
          geocoder_id: geocoder_id
          geocoded_value: {}
        - confidence: 0.8008282
          geocoder_id: geocoder_id
          geocoded_value: {}
        timestamp: 2000-01-23T04:56:07.000+00:00
    GeolookupResult:
      required:
      - geolookup_id
      - geolookup_value
      type: object
      properties:
        geolookup_id:
          type: string
          description: Identifier for the geospatial entity
        geolookup_value:
          type: object
          description: Resulting GeoJSON string from the lookup
      example:
        geolookup_id: geolookup_id
        geolookup_value: {}
    GeolookupResults:
      required:
      - id
      - results
      - timestamp
      type: object
      properties:
        id:
          type: string
          description: UUID describing the transaction
        timestamp:
          type: string
          description: Server time of the transaction
          format: date-time
        results:
          type: array
          description: Array of Geolookup results
          items:
            $ref: '#/components/schemas/GeolookupResult'
      example:
        id: id
        results:
        - geolookup_id: geolookup_id
          geolookup_value: {}
        - geolookup_id: geolookup_id
          geolookup_value: {}
        timestamp: 2000-01-23T04:56:07.000+00:00
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          style: simple
          explode: false
          schema:
            type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      x-basicInfoFunc: cape_of_good_place_names.controllers.authorization_controller.check_basicAuth

